# Generated by Django 3.2.6 on 2021-08-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_mentor_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='full_description',
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание курса'),
        ),
    ]
